mode: ContinuousDelivery
branches:
  main:
    regex: ^master$|^main$
    mode: ContinuousDelivery
    tag: ''
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: true
  
  develop:
    regex: ^dev(elop)?(ment)?$
    mode: ContinuousDeployment
    tag: dev
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
    tracks-release-branches: true
    is-release-branch: false
    is-mainline: false
  
  stage:
    regex: ^stage$|^staging$
    mode: ContinuousDelivery
    tag: stage
    increment: Patch
    prevent-increment-of-merged-branch-version: true
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
  
  feature:
    regex: ^feature?[/-]
    mode: ContinuousDeployment
    tag: feature
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false
  
  hotfix:
    regex: ^hotfix?[/-]
    mode: ContinuousDeployment
    tag: hotfix
    increment: Patch
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
    tracks-release-branches: false
    is-release-branch: false
    is-mainline: false

ignore:
  sha: []

merge-message-formats: {}

major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
no-bump-message: '\+semver:\s?(none|skip)'

tag-prefix: 'v'
version-in-branch-pattern: (?<version>[vV]?\d+\.\d+\.\d+).*
